jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MY_SECRET: ${{ secrets.MY_SECRET }}
          envkey_ANOTHER_SECRET: ${{ secrets.ANOTHER_SECRET }}
